include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "build/**"
    - "coverage/**"
    - "assets/**"
    - "**.g.dart"
    - "**.gql.dart"
    - "**.freezed.dart"
    - "**.config.dart"
    - "**.mocks.dart"
    - "**.gen.dart"
    - "**.pb.dart"
    - "**.pbenum.dart"
    - "**.pbjson.dart"
    # Flutter Version Manager
    - ".fvm/**"
    # Tools
    #- "tool/**"
    - "scripts/**"
    - ".dart_tool/**"
    # Platform
    - "ios/**"
    - "android/**"
    - "web/**"
    - "macos/**"
    - "windows/**"
    - "linux/**"

  # Enable the following options to enable strong mode.
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  errors:
    # Allow having TODOs in the code
    todo: ignore

    # Info
    directives_ordering: info
    always_declare_return_types: info

    # Warning
    unsafe_html: warning
    missing_return: warning
    missing_required_param: warning
    empty_catches: warning
    avoid_print: warning

    # Error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_types_as_parameter_names: error
    valid_regexps: error
    always_require_non_null_named_parameters: error
    avoid_dynamic_calls: error
    avoid_empty_else: error
    avoid_returning_null_for_future: error
    avoid_type_to_string: error
    avoid_web_libraries_in_flutter: error
    cancel_subscriptions: error
    close_sinks: error
    comment_references: error
    control_flow_in_finally: error
    empty_statements: error
    hash_and_equals: error
    iterable_contains_unrelated_type: error
    list_remove_unrelated_type: error
    literal_only_boolean_expressions: error
    no_adjacent_strings_in_list: error
    no_duplicate_case_values: error
    no_logic_in_create_state: error
    prefer_void_to_null: error
    test_types_in_equals: error
    throw_in_finally: error
    unnecessary_statements: error
    unrelated_type_equality_checks: error
    use_build_context_synchronously: error
    use_key_in_widget_constructors: error

linter:
  rules:
    # Public packages
    #public_member_api_docs: true
    #lines_longer_than_80_chars: true

    # Enabling rules
    always_use_package_imports: true
    avoid_relative_lib_imports: true

    # Disable rules
    sort_pub_dependencies: false
    prefer_relative_imports: false
    avoid_slow_async_io: false


    # Enabled
    use_named_constants: true
    unnecessary_constructor_name: true
    sort_constructors_first: true
    exhaustive_cases: true
    sort_unnamed_constructors_first: true
    type_literal_in_constant_pattern: true
    always_put_required_named_parameters_first: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_double_and_int_checks: true
    avoid_field_initializers_in_const_classes: true
    avoid_implementing_value_types: true
    avoid_js_rounded_ints: true
    avoid_print: true
    avoid_renaming_method_parameters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    control_flow_in_finally: true
    empty_statements: true
    collection_methods_unrelated_type: true
    join_return_with_assignment: true
    leading_newlines_in_multiline_strings: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    only_throw_errors: true
    overridden_fields: true
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_foreach: false
    prefer_if_elements_to_conditional_expressions: true
    prefer_inlined_adds: true
    prefer_int_literals: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_typing_uninitialized_variables: true
    prefer_void_to_null: true
    provide_deprecation_message: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_null_aware_assignments: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_statements: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
    use_raw_strings: true
    use_string_buffers: true
    valid_regexps: true
    void_checks: true

    # Pedantic 1.9.0
    always_declare_return_types: true
    annotate_overrides: true
    avoid_empty_else: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_return_types_on_setters: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    camel_case_extensions: true
    empty_catches: true
    empty_constructor_bodies: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    null_closures: true
    omit_local_variable_types: false
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_generic_function_type_aliases: true
    prefer_if_null_operators: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    unrelated_type_equality_checks: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true

    # Effective_dart 1.2.0
    camel_case_types: true
    file_names: true
    non_constant_identifier_names: true
    constant_identifier_names: true
    directives_ordering: true
    implementation_imports: true
    prefer_interpolation_to_compose_strings: true
    unnecessary_brace_in_string_interps: true
    avoid_function_literals_in_foreach_calls: true
    prefer_function_declarations_over_variables: true
    unnecessary_lambdas: true
    unnecessary_getters_setters: true
    prefer_initializing_formals: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    use_to_and_as_if_applicable: true
    avoid_classes_with_only_static_members: false
    prefer_mixin: true
    use_setters_to_change_properties: true
    avoid_setters_without_getters: true
    avoid_returning_this: true
    type_annotate_public_apis: true
    avoid_types_on_closure_parameters: true
    avoid_private_typedef_functions: true
    avoid_positional_boolean_parameters: true
    hash_and_equals: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    # Const rules.
    unnecessary_late: true

    # Error rules.
    avoid_dynamic_calls: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    avoid_web_libraries_in_flutter: true
    comment_references: true
    iterable_contains_unrelated_type: true
    list_remove_unrelated_type: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true

    # Style rules.
    always_put_control_body_on_new_line: false
    always_require_non_null_named_parameters: true
    always_specify_types: false
    avoid_escaping_inner_quotes: true
    avoid_final_parameters: true
    avoid_multiple_declarations_per_line: true
    avoid_redundant_argument_values: true
    cast_nullable_to_non_nullable: true
    combinators_ordering: true
    conditional_uri_does_not_exist: true
    curly_braces_in_flow_control_structures: true
    dangling_library_doc_comments: true
    depend_on_referenced_packages: true
    deprecated_consistency: true
    deprecated_member_use_from_same_package: true
    diagnostic_describe_all_properties: false
    discarded_futures: false
    do_not_use_environment: true
    enable_null_safety: true
    eol_at_end_of_file: true
    flutter_style_todos: true
    implicit_call_tearoffs: false
    implicit_reopen: true
    invalid_case_patterns: true
    library_annotations: true
    library_private_types_in_public_api: true
    lines_longer_than_80_chars: false
    matching_super_parameters: true
    no_default_cases: false
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    no_literal_bool_comparisons: true
    noop_primitive_operations: true
    null_check_on_nullable_type_parameter: true
    one_member_abstracts: false
    prefer_double_quotes: false
    prefer_equal_for_default_values: true
    prefer_final_locals: true
    prefer_null_aware_method_calls: true
    public_member_api_docs: false
    secure_pubspec_urls: true
    sized_box_shrink_expand: true
    tighten_type_of_initializing_formals: true
    unnecessary_await_in_return: true
    unnecessary_breaks: true
    unnecessary_final: false
    unnecessary_library_directive: true
    unnecessary_null_aware_operator_on_extension_on_nullable: true
    unnecessary_null_checks: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_to_list_in_spreads: true
    unreachable_from_main: false
    use_colored_box: true
    use_decorated_box: true
    use_enums: true
    use_if_null_to_convert_nulls_to_bools: true
    use_is_even_rather_than_modulo: true
    use_late_for_private_fields_and_variables: true
    use_string_in_part_of_directives: true
    use_super_parameters: true
    use_test_throws_matchers: true
    require_trailing_commas: true

